# Generated by Django 4.0.2 on 2022-02-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_acionamento_notificacao_sensor_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='switch_bool',
            new_name='status_bool',
        ),
    ]
